import { db } from "./client";
import {
  menuCategories,
  menuItems,
  mesas,
  galeriaFotos,
  eventosProgramacion,
} from "./schema";

async function seed() {
  console.log("Seeding database...");

  const [tapas, especialidades, raciones] = await db
    .insert(menuCategories)
    .values([
      { nombre: "Tapas Clásicas", descripcion: "Las tapas de siempre con el toque del Bar de Eric", orden: 1 },
      { nombre: "Especialidades de la Casa", descripcion: "Platos únicos inspirados en la música", orden: 2 },
      { nombre: "Raciones", descripcion: "Para compartir al ritmo de buena música", orden: 3 },
      { nombre: "Bebidas", descripcion: "Cervezas, vinos y cócteles rockeros", orden: 4 },
    ])
    .returning();

  await db.insert(menuItems).values([
    {
      categoryId: tapas.id,
      nombre: "Inercia",
      slug: "inercia",
      descripcion: "Croquetas de jamón ibérico",
      receta: "Croquetas caseras de jamón ibérico con bechamel cremosa",
      precio: 600,
      imagen: "/images/menu/tapa-1.svg",
      historiaMusicales: "Tema de Lagartija Nick, banda granadina de rock alternativo",
      alergenos: ["gluten", "lácteos", "huevo"],
      banda: "Lagartija Nick",
      anio: 1992,
      orden: 1,
    },
    {
      categoryId: especialidades.id,
      nombre: "Omega",
      slug: "omega",
      descripcion: "Tabla de quesos artesanos y jamón ibérico",
      receta: "Selección de quesos curados, semicurados y jamón ibérico de bellota",
      precio: 1200,
      imagen: "/images/menu/tapa-2.svg",
      historiaMusicales: "Del disco Omega de Lagartija Nick con Enrique Morente, fusión flamenca y rock",
      alergenos: ["lácteos"],
      banda: "Lagartija Nick + Enrique Morente",
      anio: 1996,
      orden: 1,
    },
    {
      categoryId: tapas.id,
      nombre: "Qué Puedo Hacer",
      slug: "que-puedo-hacer",
      descripcion: "Camarones al ajillo con guindilla",
      receta: "Camarones frescos salteados al ajillo con un toque de guindilla",
      precio: 700,
      imagen: "/images/menu/tapa-3.svg",
      historiaMusicales: "Canción de Los Planetas, banda insignia de la escena indie granadina",
      alergenos: ["crustáceos"],
      banda: "Los Planetas",
      anio: 2000,
      orden: 2,
    },
    {
      categoryId: tapas.id,
      nombre: "Pop",
      slug: "pop",
      descripcion: "Croquetas de champiñones y trufa",
      receta: "Croquetas gourmet de champiñones silvestres con aceite de trufa",
      precio: 500,
      imagen: "/images/menu/tapa-4.svg",
      historiaMusicales: "Tema del primer disco de Los Planetas, sonido lo-fi granadino",
      alergenos: ["gluten", "lácteos", "huevo"],
      banda: "Los Planetas",
      anio: 1994,
      orden: 3,
    },
    {
      categoryId: raciones.id,
      nombre: "Keith Moon",
      slug: "keith-moon",
      descripcion: "Surtido especial de carnes a la brasa",
      receta: "Selección de carnes ibéricas a la brasa con patatas y pimientos",
      precio: 1000,
      imagen: "/images/menu/tapa-5.svg",
      historiaMusicales: "En honor al legendario batería de The Who",
      alergenos: [],
      banda: "The Who",
      anio: undefined,
      orden: 1,
    },
    {
      categoryId: tapas.id,
      nombre: "Un Buen Día",
      slug: "un-buen-dia",
      descripcion: "Ensaladilla rusa de la casa",
      receta: "Ensaladilla rusa con atún, aceitunas y mayonesa casera",
      precio: 550,
      imagen: "/images/menu/tapa-6.svg",
      historiaMusicales: "Clásico de Los Planetas del disco Super 8",
      alergenos: ["huevo", "pescado"],
      banda: "Los Planetas",
      anio: 1996,
      orden: 4,
    },
    {
      categoryId: tapas.id,
      nombre: "Lagartija",
      slug: "lagartija",
      descripcion: "Mini hamburguesas con cebolla caramelizada",
      receta: "Tres mini hamburguesas de ternera con cebolla caramelizada y queso",
      precio: 800,
      imagen: "/images/menu/tapa-7.svg",
      historiaMusicales: "Inspirada en Nick Cave y el nombre de la mítica banda granadina",
      alergenos: ["gluten", "lácteos"],
      banda: "Nick Cave",
      anio: undefined,
      orden: 5,
    },
    {
      categoryId: tapas.id,
      nombre: "Joe Strummer",
      slug: "joe-strummer",
      descripcion: "Nachos con guacamole y pico de gallo",
      receta: "Nachos crujientes con guacamole fresco, pico de gallo y jalapeños",
      precio: 750,
      imagen: "/images/menu/tapa-8.svg",
      historiaMusicales: "Homenaje al líder de The Clash, punk rock con alma",
      alergenos: ["gluten"],
      banda: "The Clash",
      anio: undefined,
      orden: 6,
    },
    {
      categoryId: tapas.id,
      nombre: "091",
      slug: "091",
      descripcion: "Patatas bravas con alioli casero",
      receta: "Patatas fritas con salsa brava picante y alioli hecho en casa",
      precio: 450,
      imagen: "/images/menu/tapa-9.svg",
      historiaMusicales: "Nombre de la mítica banda granadina, prefijo telefónico de Granada",
      alergenos: ["huevo"],
      banda: "091",
      anio: undefined,
      orden: 7,
    },
    {
      categoryId: especialidades.id,
      nombre: "Los Evangelistas",
      slug: "los-evangelistas",
      descripcion: "Tabla mixta para compartir",
      receta: "Gran tabla con embutidos ibéricos, quesos, aceitunas y picos",
      precio: 1400,
      imagen: "/images/menu/tapa-10.svg",
      historiaMusicales: "La banda de Eric, el alma musical del bar",
      alergenos: ["gluten", "lácteos"],
      banda: "Los Evangelistas",
      anio: undefined,
      orden: 2,
    },
    {
      categoryId: tapas.id,
      nombre: "Lux Interior",
      slug: "lux-interior",
      descripcion: "Alitas de pollo al estilo rock",
      receta: "Alitas de pollo marinadas con salsa barbacoa y especias",
      precio: 650,
      imagen: "/images/menu/tapa-11.svg",
      historiaMusicales: "Vocalista de The Cramps, icono del garage punk",
      alergenos: [],
      banda: "The Cramps",
      anio: undefined,
      orden: 8,
    },
    {
      categoryId: tapas.id,
      nombre: "Sonic Youth",
      slug: "sonic-youth",
      descripcion: "Gazpacho andaluz con guarnición",
      receta: "Gazpacho tradicional andaluz con picatostes y verduras picadas",
      precio: 400,
      imagen: "/images/menu/tapa-12.svg",
      historiaMusicales: "Banda neoyorquina de noise rock, influencia clave del indie",
      alergenos: ["gluten"],
      banda: "Sonic Youth",
      anio: undefined,
      orden: 9,
    },
    {
      categoryId: especialidades.id,
      nombre: "Patti Smith",
      slug: "patti-smith",
      descripcion: "Tosta de salmón ahumado con alcaparras",
      receta: "Tosta de pan artesano con salmón ahumado, queso crema y alcaparras",
      precio: 850,
      imagen: "/images/menu/tapa-13.svg",
      historiaMusicales: "La madrina del punk, poeta y rockera",
      alergenos: ["gluten", "lácteos", "pescado"],
      banda: "Patti Smith",
      anio: undefined,
      orden: 3,
    },
    {
      categoryId: tapas.id,
      nombre: "Satisfaction",
      slug: "satisfaction",
      descripcion: "Montadito de lomo con pimientos",
      receta: "Montadito de lomo adobado con pimientos asados en pan crujiente",
      precio: 500,
      imagen: "/images/menu/tapa-14.svg",
      historiaMusicales: "El himno de los Rolling Stones que nunca pasa de moda",
      alergenos: ["gluten"],
      banda: "Rolling Stones",
      anio: undefined,
      orden: 10,
    },
    {
      categoryId: raciones.id,
      nombre: "London Calling",
      slug: "london-calling",
      descripcion: "Fish & chips con salsa tártara",
      receta: "Filetes de bacalao rebozados con patatas fritas y salsa tártara casera",
      precio: 900,
      imagen: "/images/menu/tapa-15.svg",
      historiaMusicales: "Álbum legendario de The Clash, punk meets rock",
      alergenos: ["gluten", "huevo", "pescado"],
      banda: "The Clash",
      anio: undefined,
      orden: 2,
    },
  ]);

  await db.insert(mesas).values([
    { numero: 1, capacidad: 2, ubicacion: "interior" },
    { numero: 2, capacidad: 2, ubicacion: "interior" },
    { numero: 3, capacidad: 4, ubicacion: "interior" },
    { numero: 4, capacidad: 4, ubicacion: "interior" },
    { numero: 5, capacidad: 4, ubicacion: "interior" },
    { numero: 6, capacidad: 6, ubicacion: "interior" },
    { numero: 7, capacidad: 6, ubicacion: "terraza" },
    { numero: 8, capacidad: 4, ubicacion: "terraza" },
    { numero: 9, capacidad: 4, ubicacion: "terraza" },
    { numero: 10, capacidad: 2, ubicacion: "terraza" },
  ]);

  await db.insert(galeriaFotos).values([
    { titulo: "Lagartija Nick en directo", descripcion: "Concierto de Lagartija Nick en el Bar de Eric, 2019", urlFoto: "/images/museo/foto-1.svg", banda: "Lagartija Nick", anio: 2019, artista: "Lagartija Nick", categoria: "conciertos", orden: 1, destacada: true },
    { titulo: "Los Planetas - Noche indie", descripcion: "Los Planetas tocando en acústico", urlFoto: "/images/museo/foto-2.svg", banda: "Los Planetas", anio: 2018, artista: "Los Planetas", categoria: "conciertos", orden: 2, destacada: true },
    { titulo: "091 - Reunión legendaria", descripcion: "091 en su paso por Granada", urlFoto: "/images/museo/foto-3.svg", banda: "091", anio: 2015, artista: "091", categoria: "conciertos", orden: 3, destacada: true },
    { titulo: "Eric con su guitarra", descripcion: "Eric Jiménez tocando en el bar", urlFoto: "/images/museo/foto-4.svg", banda: "Los Evangelistas", anio: 2020, artista: "Eric Jiménez", categoria: "el-bar", orden: 4, destacada: true },
    { titulo: "Noche de blues", descripcion: "Jam session de blues en directo", urlFoto: "/images/museo/foto-5.svg", anio: 2021, categoria: "conciertos", orden: 5 },
    { titulo: "Vinilo firmado por Enrique Morente", descripcion: "Vinilo de Omega firmado por Morente", urlFoto: "/images/museo/foto-6.svg", banda: "Enrique Morente", anio: 1996, artista: "Enrique Morente", categoria: "memorabilia", orden: 6 },
    { titulo: "Cartel original Nirvana 1991", descripcion: "Cartel de la gira Nevermind de Nirvana", urlFoto: "/images/museo/foto-7.svg", banda: "Nirvana", anio: 1991, categoria: "memorabilia", orden: 7, destacada: true },
    { titulo: "La barra del bar", descripcion: "Vista de la mítica barra llena de pegatinas y recuerdos", urlFoto: "/images/museo/foto-8.svg", anio: 2022, categoria: "el-bar", orden: 8 },
    { titulo: "Guitarra de Joe Strummer", descripcion: "Réplica de la Telecaster de Joe Strummer", urlFoto: "/images/museo/foto-9.svg", banda: "The Clash", artista: "Joe Strummer", categoria: "memorabilia", orden: 9 },
    { titulo: "Los Evangelistas en festival", descripcion: "Los Evangelistas en el festival de rock de Granada", urlFoto: "/images/museo/foto-10.svg", banda: "Los Evangelistas", anio: 2023, artista: "Los Evangelistas", categoria: "conciertos", orden: 10 },
    { titulo: "Noche de punk rock", descripcion: "Concierto punk en el Bar de Eric", urlFoto: "/images/museo/foto-11.svg", anio: 2022, categoria: "conciertos", orden: 11 },
    { titulo: "Vinilos en la pared", descripcion: "Colección de vinilos decorando el bar", urlFoto: "/images/museo/foto-12.svg", anio: 2020, categoria: "el-bar", orden: 12 },
    { titulo: "Jam session acústica", descripcion: "Músicos locales en sesión improvisada", urlFoto: "/images/museo/foto-13.svg", anio: 2023, categoria: "conciertos", orden: 13 },
    { titulo: "Cartel Sonic Youth", descripcion: "Póster original de Sonic Youth", urlFoto: "/images/museo/foto-14.svg", banda: "Sonic Youth", categoria: "memorabilia", orden: 14 },
    { titulo: "Fachada del bar", descripcion: "La entrada del Bar de Eric en el Realejo", urlFoto: "/images/museo/foto-15.svg", anio: 2024, categoria: "el-bar", orden: 15 },
    { titulo: "Patti Smith - Poesía y rock", descripcion: "Homenaje a Patti Smith en el bar", urlFoto: "/images/museo/foto-16.svg", banda: "Patti Smith", artista: "Patti Smith", categoria: "memorabilia", orden: 16 },
    { titulo: "Noche de garage rock", descripcion: "Banda local de garage rock en directo", urlFoto: "/images/museo/foto-17.svg", anio: 2024, categoria: "conciertos", orden: 17 },
    { titulo: "Colección de púas", descripcion: "Púas de guitarra firmadas por músicos", urlFoto: "/images/museo/foto-18.svg", categoria: "memorabilia", orden: 18 },
    { titulo: "Terraza del bar", descripcion: "La terraza en una noche de verano", urlFoto: "/images/museo/foto-19.svg", anio: 2023, categoria: "el-bar", orden: 19 },
    { titulo: "Festival Rock en el Barrio", descripcion: "El Bar de Eric participando en el festival del barrio", urlFoto: "/images/museo/foto-20.svg", anio: 2024, categoria: "conciertos", orden: 20, destacada: true },
  ]);

  await db.insert(eventosProgramacion).values([
    {
      titulo: "Lagartija Nick - 30 Aniversario",
      slug: "lagartija-nick-30-aniversario",
      tipo: "concierto",
      descripcion: "Lagartija Nick celebra 30 años de rock granadino en el Bar de Eric",
      fecha: "2025-09-20",
      hora: "22:00",
      artistaBanda: "Lagartija Nick",
      aforoMaximo: 80,
      entradaLibre: false,
      precioEntrada: 1500,
      imagen: "/images/eventos/concierto.svg",
      estado: "programado",
    },
    {
      titulo: "Noche de Los Planetas",
      slug: "noche-de-los-planetas",
      tipo: "concierto",
      descripcion: "Tributo a Los Planetas con bandas locales de Granada",
      fecha: "2025-10-15",
      hora: "21:30",
      artistaBanda: "Varios artistas",
      aforoMaximo: 60,
      entradaLibre: true,
      imagen: "/images/eventos/concierto.svg",
      estado: "programado",
    },
    {
      titulo: "Jam Session Blues",
      slug: "jam-session-blues",
      tipo: "jam-session",
      descripcion: "Sesión abierta de blues, trae tu instrumento y únete",
      fecha: "2025-11-05",
      hora: "21:00",
      aforoMaximo: 50,
      entradaLibre: true,
      imagen: "/images/eventos/taller.svg",
      estado: "programado",
    },
    {
      titulo: "Los Evangelistas en Navidad",
      slug: "los-evangelistas-navidad",
      tipo: "concierto",
      descripcion: "Concierto especial de Navidad con Los Evangelistas",
      fecha: "2025-12-23",
      hora: "22:00",
      artistaBanda: "Los Evangelistas",
      aforoMaximo: 70,
      entradaLibre: false,
      precioEntrada: 1000,
      imagen: "/images/eventos/concierto.svg",
      estado: "programado",
    },
    {
      titulo: "Noche de Punk Rock",
      slug: "noche-punk-rock",
      tipo: "concierto",
      descripcion: "Las mejores bandas punk de Granada en una noche explosiva",
      fecha: "2026-01-17",
      hora: "22:30",
      artistaBanda: "Varios artistas",
      aforoMaximo: 80,
      entradaLibre: false,
      precioEntrada: 800,
      imagen: "/images/eventos/concierto.svg",
      estado: "programado",
    },
    {
      titulo: "Cata de Vinos y Vinilo",
      slug: "cata-vinos-vinilo",
      tipo: "cata",
      descripcion: "Maridaje de vinos andaluces con música en vinilo",
      fecha: "2026-02-14",
      hora: "20:00",
      aforoMaximo: 30,
      entradaLibre: false,
      precioEntrada: 2500,
      imagen: "/images/eventos/exposicion.svg",
      estado: "programado",
    },
    {
      titulo: "Festival Indie Primavera",
      slug: "festival-indie-primavera",
      tipo: "festival",
      descripcion: "Mini festival con las nuevas promesas del indie granadino",
      fecha: "2026-04-18",
      hora: "19:00",
      artistaBanda: "Varios artistas",
      aforoMaximo: 100,
      entradaLibre: false,
      precioEntrada: 1200,
      imagen: "/images/eventos/guia-rockera.svg",
      estado: "programado",
    },
    {
      titulo: "Homenaje a Enrique Morente",
      slug: "homenaje-enrique-morente",
      tipo: "concierto",
      descripcion: "Noche flamenca en honor al maestro Morente",
      fecha: "2026-05-22",
      hora: "21:00",
      artistaBanda: "Artistas flamencos invitados",
      aforoMaximo: 60,
      entradaLibre: true,
      imagen: "/images/eventos/concierto.svg",
      estado: "programado",
    },
    {
      titulo: "Aniversario del Bar de Eric",
      slug: "aniversario-bar-eric",
      tipo: "festival",
      descripcion: "Celebración del aniversario con música en directo todo el día",
      fecha: "2026-06-21",
      hora: "18:00",
      artistaBanda: "Los Evangelistas y amigos",
      aforoMaximo: 120,
      entradaLibre: true,
      imagen: "/images/eventos/guia-rockera.svg",
      estado: "programado",
    },
    {
      titulo: "Noche de Garage Rock",
      slug: "noche-garage-rock",
      tipo: "concierto",
      descripcion: "Rock de garaje crudo y directo como debe ser",
      fecha: "2026-07-10",
      hora: "22:00",
      artistaBanda: "The Fuzz Bombs + Los Reactivos",
      aforoMaximo: 70,
      entradaLibre: false,
      precioEntrada: 600,
      imagen: "/images/eventos/concierto.svg",
      estado: "programado",
    },
  ]);

  console.log("Seed completed successfully!");
}

seed()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  });
